
##
## Kubernetes configuration for hello-kubernetes simple demo.
##

apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-service
spec:
  type: LoadBalancer
  ports:
      # port of pod to contact
    - targetPort: 8050
      # within the cluster
      port: 8050
      # outside the cluster
      nodePort: 30000
  selector:
    app: hello-kubernetes
---

apiVersion: apps/v1
kind: Deployment
# This describes the actual deployment:
metadata:
  name: hello-kubernetes-deployment
  labels:
    app: hello-kubernetes
spec:
  replicas: 1
  template:
    # This describes what pods to create:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      containers:
        - name: hello-kubernetes
          image: paulbouwer/hello-kubernetes:1.8
          imagePullPolicy: IfNotPresent
          env:
            - name: MESSAGE
              value: Custom message by Mark
            - name: PORT
              value: "8050"
  # This describes which pods are part of the deployment,
  # so this should match 'metadata' in almost all cases:
  selector:
    matchLabels:
      app: hello-kubernetes

