
##
## Kubernetes configuration for k8s_host_db demo project.
##

#TODO @mark: start of temporary demo

# hello-kubernetes.yaml
apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8050
  selector:
    app: hello-kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-kubernetes
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      containers:
        - name: hello-kubernetes
          image: paulbouwer/hello-kubernetes:1.8
          ports:
            - containerPort: 8050
---

#TODO @mark: end of temporary demo

## Start a service that makes the outside DB accessible in the cluster.
## See: https://stackoverflow.com/a/43477742
## If your database is inside the k8s cluster, you can skip this part.

kind: Service
apiVersion: v1
metadata:
  name: host-db-service
spec:
  ports:
      # this is the port inside the cluster
      # it can be the same as below, but we make it different to know which one we are using
    - port: 3006
      # this is the port outside the cluster (3005 is value from README.md)
      targetPort: 3005

---
kind: Endpoints
apiVersion: v1
metadata:
  name: host-db-service
subsets:
  - addresses:
      - ip: 10.0.2.2
    ports:
      - port: 3005


## Start the mock database inside the cluster.
## If your database is outside the k8s cluster, you can skip this part.

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mock-db-inside
spec:
  selector:
    matchLabels:
      app: mock-db-inside
  replicas: 1
  template:
    metadata:
      labels:
        app: mock-db-inside
    spec:
      containers:
        - name: mock-db-inside
          image: mock-db
          imagePullPolicy: Never
          ports:
              # Use a different port from the outside database
            - containerPort: 2005


## Start the mock client inside the cluster.
## Replace this by your application that uses the database.

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mock-client
spec:
  selector:
    matchLabels:
      app: mock-client
  replicas: 1
  template:
    metadata:
      labels:
        app: mock-client
    spec:
      containers:
        - name: mock-client
          image: mock-client
          imagePullPolicy: Never
          ports:
              # Use a different port from the outside database
            - containerPort: 8088

## Expose the above client to the outside world, so we can see it.

---

apiVersion: v1
kind: Service
metadata:
  name: mock-client-service
spec:
  type: LoadBalancer
  selector:
    app: mock-client
  ports:
    - port: 8088
      targetPort: 31088

---
#apiVersion: networking.k8s.io/v1
## If Ingress is not recognized, update your Kubernetes version
#kind: Ingress
#metadata:
#  name: mock-client-ingress
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /$1
#spec:
#  rules:
#    - host: local.example
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: mock-client-service
#                port:
#                  number: 8080
