
## Kubernetes configuration for k8s_host_db demo project

## Start a service that makes the outside DB accessible in the cluster
## See: https://stackoverflow.com/a/43477742
## If your database is inside the k8s cluster, you can skip this part.

kind: Service
apiVersion: v1
metadata:
  name: host-db-service
spec:
  ports:
      # this is the port inside the cluster
      # it can be the same as below, but we make it different to know which one we are using
    - port: 3006
      # this is the port outside the cluster (3005 is value from README.md)
      targetPort: 3005

---
kind: Endpoints
apiVersion: v1
metadata:
  name: host-db-service
subsets:
  - addresses:
      - ip: 10.0.2.2
    ports:
      - port: 3005


## Start the mock database inside the cluster
## If your database is outside the k8s cluster, you can skip this part.

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mock-db-inside
spec:
  selector:
    matchLabels:
      app: mock-db-inside
  replicas: 2
  template:
    metadata:
      labels:
        app: mock-db-inside
    spec:
      containers:
        - name: mock-db-inside
          image: mock-db
          imagePullPolicy: Never
          ports:
              # Use a different port from the outside database
            - containerPort: 2005
